stepik_vacancies/urls.py
import debug_toolbar

from django.conf import settings

from django.contrib import admin

from django.urls import include, path

from vacancies.views import custom_handler404, custom_handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vacancies.urls')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = custom_handler404

handler500 = custom_handler500

vacancies/urls.py
from django.urls import path

from .views import AllVacanciesView, CompanyDetail, IndexView, VacanciesBySpecialtyView, VacancyDetail


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('vacancies', AllVacanciesView.as_view(), name='vacancies'),
    path('vacancies/cat/<slug:specialty>', VacanciesBySpecialtyView.as_view(), name='vacancies_by_specialty'),
    path('companies/<int:pk>', CompanyDetail.as_view(), name='companies'),
    path('vacancies/<int:pk>', VacancyDetail.as_view(), name='vacancy'),

]

vacancies/models.py
from django.db import models


class Vacancy(models.Model):
    title = models.CharField(max_length=100)
    specialty = models.ForeignKey('Specialty', on_delete=models.CASCADE, related_name='vacancies')
    company = models.ForeignKey('Company', on_delete=models.CASCADE, related_name='vacancies')
    skills = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    salary_min = models.IntegerField()
    salary_max = models.IntegerField()
    published_at = models.DateField()


class Company(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    logo = models.URLField(default='https://place-hold.it/100x60')
    description = models.TextField(max_length=100)
    employee_count = models.IntegerField()


class Specialty(models.Model):
    code = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    picture = models.URLField(default='https://place-hold.it/100x60')

vacancies/views.py
from django.http import HttpResponseNotFound, HttpResponseServerError
from django.views.generic import DetailView, ListView

from vacancies.models import Company, Specialty, Vacancy


class IndexView(ListView):
    model = Specialty
    template_name = 'vacancies/index.html'
    context_object_name = 'specialties'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['specialties'] = Specialty.objects.all().prefetch_related('vacancies')
        context['companies'] = Company.objects.all().prefetch_related('vacancies')
        return context


class AllVacanciesView(ListView):
    model = Vacancy
    template_name = 'vacancies/all_vacancies.html'

    def get_queryset(self):
        return Vacancy.objects.all().select_related('company').select_related('specialty')


class VacanciesBySpecialtyView(ListView):
    model = Vacancy
    template_name = 'vacancies/specialty_vacancies.html'
    context_object_name = 'vacancies'

    def get_queryset(self):
        return Vacancy.objects.filter(specialty__code=self
                                      .kwargs['specialty'])\
                                      .select_related('specialty')\
                                      .select_related('company')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['specialty_name'] = Specialty.objects.filter(code=self.kwargs['specialty'])[0].title
        return context


class CompanyDetail(DetailView):
    model = Company
    template_name = 'vacancies/company.html'
    pk_url_kwarg = 'pk'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vacancies'] = Vacancy.objects.filter(company=self.kwargs['pk']).select_related('specialty')
        return context


class VacancyDetail(DetailView):
    model = Vacancy
    template_name = 'vacancies/vacancy.html'
    pk_url_kwarg = 'pk'

    def get_queryset(self):
        return Vacancy.objects.filter(pk=self.kwargs['pk']).select_related('company').select_related('specialty')


def custom_handler404(request, exception):
    return HttpResponseNotFound('Здесь ничего нет')


def custom_handler500(request):
    return HttpResponseServerError('На сервере что-то сломалось')

vacancies/templates/vacancies/all_vacancies.html
{% extends 'vacancies/base.html' %}

{% block content %}

  <main class="container mt-3">
    <section>
      <h1 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;"><strong>Все вакансии</strong></h1>
      <p class="text-center pt-1">{{ vacancy_list|length }} вакансий</p>
      <div class="row mt-5">
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
          {% for vacancy in vacancy_list %}
          <div class="card mb-4">
            <div class="card-body px-4">
              <div class="row">
                <div class="col-12 col-md-8 col-lg-9">
                  <h2 class="h2 pb-2">{{ vacancy.title }}</h2>
                  <p class="mb-2">{{ vacancy.skills }}</p>
                  <p>От {{ vacancy.salary_min }} до {{ vacancy.salary_max }} руб.</p>
                  <p class="text-muted pt-1">{{ vacancy.published_at }}</p>
                </div>
                <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                  <a href="#"><img src="../static/{{ vacancy.company.logo }}" width="130" height="80" alt=""></a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

    </section>
  </main>

{% endblock %}

vacancies/templates/vacancies/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Компания | Джуманджи</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
</head>

<body>
  <header class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mr-4 font-weight-bold" href="/">Джуманджи</a>
      <button class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarNav"
              aria-controls="navbarNav"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav col-10">
          <li class="nav-item">
            <a class="nav-link" href="#">Вакансии</a>
          </li>

        </ul>
        <ul class="navbar-nav col-2 justify-content-end">
          <li class="nav-item active">
            <a href="#" class="nav-link font-weight-bold">Вход</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

{% block content %}
{% endblock %}

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"></script>
</body>
</html>

vacancies/templates/vacancies/company-create.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Создать карточку компании | Джуманджи</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    body {
      background-color: #F6F2E6;
    }
  </style>
</head>

<body>
  <header class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mr-4 font-weight-bold" href="#">Джуманджи</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav col-10">
          <li class="nav-item">
            <a class="nav-link text-dark" href="#">Вакансии</a>
          </li>

        </ul>
        <ul class="navbar-nav col-2 justify-content-end">
          <li class="nav-item active">
            <div class="btn-group">
              <button type="button" class="btn dropdown-toggle font-weight-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Иван Топорыжкин
              </button>
              <div class="dropdown-menu dropdown-menu-right mt-3">
                <a href="#" class="dropdown-item py-2">Профиль</a>
                <a href="#" class="dropdown-item py-2">Резюме</a>
                <a href="#" class="dropdown-item py-2">Компания</a>
                <a href="#" class="dropdown-item py-2">Выйти</a>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <main class="container mt-3 pb-5">
    <section class="col-12 col-lg-6 offset-lg-3 mt-5 card">
      <div class="card-body px-3 pb-4">
        <h1 class="h4 pt-2">Моя компания</h1>
        <p class="mt-2">Пока мы думаем, что вы – частное лицо. Хотите создать карточку компании, разместить информаию и вакансии?</p>
        <a href="#" class="btn btn-info mb-2">Создать карточку компании</a>
      </div>
    </section>
  </main>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

vacancies/templates/vacancies/company-edit.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Моя компания | Джуманджи</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    body {
      background-color: #F6F2E6;
    }
  </style>
</head>

<body>
  <header class="container mt-3">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mr-4 font-weight-bold" href="#">Джуманджи</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav col-10">
          <li class="nav-item">
            <a class="nav-link text-dark" href="#">Вакансии</a>
          </li>

        </ul>
        <ul class="navbar-nav col-2 justify-content-end">
          <li class="nav-item active">
            <div class="btn-group">
              <button type="button" class="btn dropdown-toggle font-weight-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Иван Топорыжкин
              </button>
              <div class="dropdown-menu dropdown-menu-right mt-3">
                <a href="#" class="dropdown-item py-2">Профиль</a>
                <a href="#" class="dropdown-item py-2">Резюме</a>
                <a href="#" class="dropdown-item py-2">Компания</a>
                <a href="#" class="dropdown-item py-2">Выйти</a>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-4">
        <aside class="pt-3 pb-4 px-4 mb-5 card">
          <h1 class="h4 pt-2 pb-2">Моя компания</h1>
          <div class="nav flex-column nav-pills">
            <a class="nav-link active" href="#">1. Информация о&nbsp;компании</a>
            <a class="nav-link" href="#">2. Вакансии</a>
          </div>
        </aside>
      </div>
      <div class="col-12 col-lg-8">
        <div class="card">
          <div class="card-body px-4 pb-4">
            <!-- Tab -->
            <section class="tab-pane fade show active">
              <h2 class="h4 pt-2 pb-3">Информация о&nbsp;компании</h2>
              <p class="alert alert-info" role="alert">
                Информация о компании обновлена
              </p>
              <form action="/echo" enctype="multipart/form-data">
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      <label class="mb-2 text-dark" for="companyName">Название компании</label>
                      <input class="form-control" type="text" value="Staffing Smarter" id="companyName">
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label class="mb-2 text-dark" for="companyLogo">Логотип</label>
                      <div class="row align-items-center">
                        <div class="col-6">
                          <img src="https://place-hold.it/120x40" alt="" style="max-width: 120px;height: auto;">
                        </div>
                        <div class="col-6" style="position: relative;">
                          <div class="input-group-prepend" style="position: absolute; top: 0;right: 15px;">
                            <span class="btn btn-info px-4">Загрузить</span>
                          </div>
                          <div class="custom-file" style="">
                            <input type="file" class="custom-file-input" id="inputGroupFile01">
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      <label class="mb-2 text-dark" for="companyTeam">Количество человек в компании</label>
                      <input class="form-control" type="text" value="10-15" id="companyTeam">
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group pb-2">
                      <label class="mb-2 text-dark" for="companyLocation">География</label>
                      <input class="form-control" type="text" value="Рязань" id="companyLocation">
                    </div>
                  </div>
                </div>
                <div class="form-group pb-2">
                  <label class="mb-2 text-dark" for="companyInfo">Информация о&nbsp;компании</label>
                  <textarea class="form-control" rows="4" id="companyInfo" style="color:#000;">Для тех, кто желает работать в&nbsp;комфортном офисе,&nbsp;&mdash; у&nbsp;нас их&nbsp;целых три. Исторически так сложилось, что руководство и&nbsp;менеджерский состав располагается в&nbsp;Москве (обусловлено близостью заказчиков), центр разработки&nbsp;&mdash; в&nbsp;Ульяновске, в&nbsp;т.&nbsp;ч. школа молодых разработчиков и&nbsp;QA-центр&nbsp;&mdash; в&nbsp;Казани.</textarea>
                </div>
                <div class="form-group">
                  <input type="submit" class="btn btn-info" value="Сохранить">
                </div>
              </form>
            </section>
            <!-- END Tab -->
          </div>
        </div>
      </div>
    </div>
  </main>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

vacancies/templates/vacancies/company.html
{% extends 'vacancies/base.html' %}

{% block content %}

  <main class="container mt-3">
    <div class="navbar mt-5">
      <p><a href="javascript:history.go(-1)">Назад</a></p>
    </div>
    <section>
      <div class="text-center">
        <img src="../static/{{ company.logo }}" width="130" height="80" alt="">
      </div>
      <h1 class="h1 text-center mx-auto mt-0 pt-1" style="font-size: 70px;"><strong>{{ company.name }}</strong></h1>
      <p class="text-center pt-1">{{ company.description}} {{ company.location }}, {{ company.vacancies.count }} вакансий</p>
      <div class="row mt-5">
        {% for vacancy in vacancies %}
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
          <div class="card mb-4">
            <div class="card-body px-4">
              <div class="row">
                <div class="col-12 col-md-8 col-lg-9">
                  <h2 class="h2 pb-2">{{ vacancy.title }}</h2>
                  <p class="mb-2">{{ vacancy.specialty.title }} • {{ vacancy.skills }}</p>
                  <p>От {{ vacancy.salary_min }} до {{ vacancy.salary_max }} руб.</p>
                  <p class="text-muted pt-1">{{ vacancy.published_at }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>
  </main>

{% endblock %}

vacancies/templates/vacancies/index.html
{% extends 'vacancies/base.html' %}

{% block content %}

  <main class="container mt-3">
    <section>
      <h1 class="h1 text-center mx-auto mt-4 py-5"><strong>Вакансии для <br>Junior-разработчиков</strong></h1>
      <div class="row">
        <div class="col-12 col-md-8 col-lg-6 offset-lg-3 offset-md-2">
          <form class="form-inline mb-3" enctype="multipart/form-data">
            <div class="form-group col-8 col-md-10 pl-0">
              <input class="form-control w-100" type="search" placeholder="Найти работу или стажировку" aria-label="Найти работу или стажировку">
            </div>
            <div class="form-group col-4 col-md-2 pl-0">
              <button class="btn btn-primary w-100" type="submit">Найти</button>
            </div>
          </form>
          <p>Например: 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">Python</a> 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">Flask</a> 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">Django</a> 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">Парсинг</a> 
            <a href="#" class="text-dark border-bottom border-dark m-1 text-decoration-none">ML</a> 

          </p>
        </div>
      </div>
    </section>

    <section class="mt-5 pt-3">
      <h2 class="h2 font-weight-normal text-center mb-5">Вакансии по рубрикам</h2>
      <div class="row mb-0">
        {% for specialty in specialties %}
        <div class="col-6 col-md-6 col-lg-3">
          <div class="card pt-4 text-center mb-4">
            <img class="mx-auto d-block" src="https://place-hold.it/80x80" width="80" height="80" alt="">
            <div class="card-body">
              <p class="card-text mb-2">{{ specialty.title }}</p>
              <p class="card-text"><a href="{% url 'vacancies_by_specialty' specialty.code %}">{{ specialty.vacancies.count }} Вакансий</a></p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>

    <section class="my-5 pt-3">
      <h2 class="h2 font-weight-normal text-center mb-5">Нам доверяют лучшие компании</h2>
      <div class="row mb-0">
        {% for company in companies %}
        <div class="col-6 col-md-6 col-lg-3">
          <div class="card pt-4 text-center mb-4">
            <a href="{% url 'companies' company.id %}" style="max-width: 150px;" class="mx-auto d-block">
              <img class="mx-auto d-block mw-100" src="../static/{{ company.logo }}" alt="">
            </a>
            <div class="card-body">
              <p class="card-text"><a href="{% url 'companies' company.id %}">{{ company.vacancies.count}} вакансий</a></p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>
  </main>

{% endblock %}

vacancies/templates/vacancies/specialty_vacancies.html
{% extends 'vacancies/base.html' %}

{% block content %}

  <main class="container mt-3">
    <section>
      <h1 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;"><strong>{{ specialty_name }}</strong></h1>
      <p class="text-center pt-1">{{ vacancies.count }} вакансий</p>
      <div class="row mt-5">
        <div class="col-12 col-lg-8 offset-lg-2 m-auto">
          {% for vacancy in vacancies %}
          <div class="card mb-4">
            <div class="card-body px-4">
              <div class="row">
                <div class="col-12 col-md-8 col-lg-9">
                  <h2 class="h2 pb-2">{{ vacancy.title }}</h2>
                  <p class="mb-2">{{ vacancy.skills }}</p>
                  <p>От {{ vacancy.salary_min }} до {{ vacancy.salary_max }} руб.</p>
                  <p class="text-muted pt-1">{{ vacancy.published_at }}</p>
                </div>
                <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                  <a href="{% url 'companies' vacancy.company_id %}"><img src="/static/{{ vacancy.company.logo }}" width="130" height="80"  alt=""></a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

    </section>
  </main>

{% endblock %}

vacancies/templates/vacancies/vacancy.html
{% extends 'vacancies/base.html' %}

{% block content %}

  <main class="container mt-3 pb-5">
    <div class="row mt-5">
      <div class="col-12 col-lg-2">
        <div class="pl-3 mb-5">
          <p><a href="#">Назад</a></p>
        </div>
      </div>
      <div class="col-12 col-lg-8">
        <section class="pl-3">
          <a href="#"><img src="../static/{{ vacancy.company.logo }}" width="130" height="80" alt=""></a>
          <div class="d-flex align-items-baseline align-content-baseline">
            <h1 class="h2 mt-4 font-weight-bold" >{{ vacancy.title }}</h1>
            <p class="m-0 pl-3">{{ vacancy.salary_min }} – {{ vacancy.salary_max }} Р</p>
          </div>
            {{ vacancy.title}}
          <p class="mt-2">{{ vacancy.specialty.title }} • {{ vacancy.skills }}</p>
          <p class="text-muted mb-4">
             {{ vacancy.company.name }}
             ({{ vacancy.company.employee_count }} человек),
             {{ vacancy.company.location }} или удаленно
          </p>
          <p>{{ vacancy.company.description }}</p>
          <div style="line-height: 1.8;">
            {{ vacancy.description|safe }}
          </div>
          <form action="/echo" class="card mt-4 mb-3" enctype="multipart/form-data">
            <div class="card-body mx-3">
              <p class="h5 mt-3 font-weight-normal">Отозваться на вакансию</p>
              <div class="form-group">
                <label class="mb-1 mt-2" for="userName">Вас зовут</label>
                <input class="form-control" type="text" placeholder="" id="userName">
              </div>
              <div class="form-group">
                <label class="mb-1" for="userPhone">Ваш телефон</label>
                <input class="form-control" type="tel" placeholder="" id="userPhone">
              </div>
              <div class="form-group">
                <label class="mb-1" for="userMsg" >Сопроводительное письмо</label>
                <textarea class="form-control" rows="8" id="userMsg"></textarea>
              </div>
              <input type="submit" class="btn btn-primary mt-4 mb-2" value="Записаться на пробный урок">
            </div>
          </form>
        </section>
      </div>
    </div>
  </main>

{% endblock %}